allowBuilds:
  "@rocicorp/zero-sqlite3": true
  esbuild: true
  protobufjs: true
packages:
  - .
  - .playground
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vitest: 4.1.10
  vite-plus: 0.2.8
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@rocicorp/zero@1.9.0"
